[Issue-1119] Adds additional validation that `--git-url` does not contain the repository path
buildpacks-community/kpack-cli pull request #329
Opened 2023-07-27 16:06 UTC by fcaroline2020

- Regex to check that there are no forward slashes after a period in the url
- prints an error if url includes path `git url should be a valid url without the repository path (ex. https://github.com)`

2023-07-28 10:49 UTC, fcaroline2020 commented
Resolves https://github.com/buildpacks-community/build-service#1119

2023-08-23 21:30 UTC, chenbh commented
I think we also need to handle the ssh case, both `git@github.com:owner` and `git@github.com:owner/repo` should fail validation.

But then having a port in an http scheme should be valid (`https://github.enterprise:1234`). There's also esoteric case like query strings (`https://github.com?query=foo.bar`).

I wonder if we should just say screw it, try to parse it via `url.Parse`, and extract the Host portion from there. Would the UX be okay as long as we print the final parsed host/domain?

2023-08-24 14:57 UTC, chenbh commented
Turns out `url.Parse` doesn't like the colon in the ssh shorthand form `git@github.com:org/repo`

2023-08-25 16:22 UTC, fcaroline2020 commented
@chenbh I'll add the ssh case and give you a heads up once its ready

2023-08-30 19:56 UTC, chenbh requested changes

2023-08-30 19:56 UTC, chenbh commented on pkg/secret/factory.go
> +		}
Let's compile these regex's as global vars, this way we can move them to the top of the file and make it easier to find and modify them.

2023-08-30 19:56 UTC, chenbh commented on pkg/secret/factory.go
> +	re := regexp.MustCompile(`^git@github\.com$`)
We have to support domains other than `github.com` and the git implementation doesn't specify that the user is always `git`

2023-09-07 21:04 UTC, chenbh approved these changes
that's some nasty regex

2023-09-08 14:34 UTC, merged